baseUrl: "https://govcloud.github.io"
theme: wxt
ContentDir: "content"
LayoutDir: "layouts"
PublishDir: "public"
BuildDrafts: true
RelativeURLs: true
LanguageCode: "en-us"
Title: "GovCloud"
PluralizeListTitles: False
menu:
  main:
    - Name: "GitHub"
      Weight: -100
      URL: "http://github.com/govcloud"
    - Name: "Registration"
      Weight: -95
      Identifier: "register"
      URL: "/register/"
Params:
  Author: "Statistics Canada: Cloud Ops Team"
  Banner: "Working group for Containers and Kubernetes"
  DateForm: "2006-01-02"
  disqusShortname: "goc"
  GoogleAnalyticsUserID: "XXXX-XXXX-XXXX"
  Github: "govcloud/govcloud.github.io"
  Search: "govcloud.ca"
  ShowRelatedPost: True
  Slogan: "Helping to build a government that is cloud native"
  SyntaxHighlightTheme: "monokai.min.css"
  Theme: "theme-gcweb"
  Twitter: "statcan_eng"
Indexes:
  tag: "tags"
permalinks:
  post: /post/:year/:month/:day/:title/
MetadataFormat: "yaml"
