baseUrl: "https://govcloud.github.io"
theme: wxt
ContentDir: "content"
LayoutDir: "layouts"
PublishDir: "public"
BuildDrafts: true
RelativeURLs: true
LanguageCode: "en-us"
Title: "GovCloud"
PluralizeListTitles: False
menu:
  main:
    - Name: "GitHub"
      Weight: -100
      Pre: <i class='fa fa-github'></i>
      URL: "http://github.com/govcloud"
    - Name: "Youtube"
      Weight: -100
      Pre: <i class='fa fa-youtube'></i>
      URL: "https://www.youtube.com/channel/UC00nN9hhb4q6IChP8yEIzGA/playlists"
    - Name: "Meetups"
      Weight: -95
      Identifier: "meetups"
      URL: "/sitemap/meetup/"
    - Name: "Feedback"
      Weight: -90
      Identifier: "feedback"
      URL: "/feedback/"
Params:
  Author: "Statistics Canada: Cloud Ops Team"
  Banner: "Working group for Containers and Kubernetes"
  DateForm: "2006-01-02"
  disqusShortname: "goc"
  GoogleAnalyticsUserID: "XXXX-XXXX-XXXX"
  Github: "govcloud/govcloud.github.io"
  Search: "govcloud.ca"
  ShowRelatedPost: True
  Slogan: "Helping to build a government that is cloud native"
  SyntaxHighlightTheme: "monokai.min.css"
  Theme: "theme-gcweb"
  Twitter: "statcan_eng"
Indexes:
  tag: "tags"
permalinks:
  post: /post/:year/:month/:day/:title/
MetadataFormat: "yaml"
